// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"database/sql"
)

type Note struct {
	ID        int64
	UserID    int64
	Content   string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type Role struct {
	ID   int64
	Name string
}

type User struct {
	ID       int64
	Username string
	Password string
	Active   bool
}

type UserRole struct {
	ID     int64
	UserID int64
	RoleID int64
}
